# ============================================
# $Id: Makefile,v 1.12 2006/11/09 09:45:37 eric Exp $
# ============================================

appname = WHAT

export appname

export targetdir
export utildir

SUBDIR= Blue

include $(utildir)/PubRule
